version: '3'

services:
  db:
    image: mysql:5.7.36
    expose:
     - 3306
    networks:
      - webapp
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=ticketmagpie
  web:
    build: .
    depends_on:
      - db
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - webapp
    volumes:
      - maven_repo:/root/.m2


networks:
  webapp:

volumes:
  maven_repo:
